version: '3.8'

services:

  chat_app_nginx:
    image: nginx:1.19-alpine
    restart: unless-stopped
    volumes:
      - ./services/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./services/nginx/sites-available:/etc/nginx/sites-available
      - ./services/nginx/logs/users_api:/var/log/nginx/users_api
      - ./services/nginx/logs/frontend:/var/log/nginx/frontend
      - ../services/users_api:/var/www/html/users_api
      - ../services/frontend:/var/www/html/frontend
    environment:
      - NGINX_HOST=${NGINX_HOST}
    ports:
      - "80:80"
    depends_on:
      - chat_app_users_api
      - chat_app_frontend

  chat_app_users_api:
    image: nanoninja/php-fpm:latest
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./services/php.ini:/usr/local/etc/php/conf.d/php.ini
      - ../services/users_api:/var/www/html/users_api
    depends_on:
      - chat_app_mysql

  chat_app_frontend:
    image: nanoninja/php-fpm:latest
    restart: unless-stopped
    volumes:
      - ./services/php.ini:/usr/local/etc/php/conf.d/php.ini
      - ../services/frontend:/var/www/html/frontend
    depends_on:
      - chat_app_mysql

  chat_app_phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: chat_app_phpmyadmin
    ports:
      - "8080:80"
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=${MYSQL_HOST}
    restart: unless-stopped
    depends_on:
      - chat_app_mysql

  chat_app_mysql:
    image: mysql:${MYSQL_VERSION}
    container_name: ${MYSQL_HOST}
    env_file:
      - .env
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_USER=${MYSQL_ROOT_USER}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - "8787:3306"
    volumes:
      - ./services/mysql/data:/var/lib/mysql